# Gravity Cluster Configuration - 1 Validator
# Node deployment configuration only

[cluster]
name = "gravity-devnet-one"
base_dir = "/tmp/gnode-1node"


[genesis_source]
genesis_path = "./artifacts/genesis.json"
waypoint_path = "./artifacts/waypoint.txt"

[[nodes]]
id = "node1"
role = "genesis"
source = { project_path = "../" }   # 复用本地已构建的 target/quick-release/gravity_node，避免重新 clone+build
host = "127.0.0.1"
validator_port = 6280
vfn_port = 6290
rpc_port = 8645
metrics_port = 9101
inspection_port = 10100
https_port = 1124
authrpc_port = 8651
reth_p2p_port = 12124

[faucet_init]
num_accounts = 10100
